name: Create-Message-Template

on:
  push:
    paths:
      - '**/create-message-template.hs'
      - 'test/'
    branches:
      - main
  pull_request:
    paths:
      - '**/create-message-template.hs'
      - 'test/'
    types:
      - opened
      - synchronize
      - reopened

jobs:
  create-message-template:
    name: Testing create-message-template.hs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
    - run: test/create-message-template/test.sh
