name: HLint

on:
  push:
    paths:
      - 'message-index/site.hs'
      - 'message-index/create-message-template.hs'
    branches:
      - main
  pull_request:
    paths:
      - 'message-index/site.hs'
      - 'message-index/create-message-template.hs'
    branches:
      - main

jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - name: Check site.hs with hlint
      uses: haskell-actions/hlint-scan@v1
      with:
        path: message-index/site.hs message-index/create-message-template.hs
        hints: message-index/.hlint.yml
