name: Pullrequest CI
on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-and-test:
    name: Build site
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["9.2.5"]
        cabal: ["3.10.1"]

    defaults:
      run:
        working-directory: message-index

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Install Haskell Toolchain
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Configure the build plan
      run: |
        cabal update
        cabal build --dry-run
      # cabal build --dry-run creates dist-newstyle/cache/plan.json
      # Keep a watch on this `cabal-3.9 build --dry-run` bug:
      # https://github.com/haskell/cabal/issues/8706

    - name: Read the Cabal cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/store
          message-index/dist-newstyle
        key: |
          cabal-cache-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-${{ hashFiles('**/plan.json') }}
        restore-keys: |
          cabal-cache-ghc-${{ matrix.ghc }}-cabal-${{ matrix.cabal }}-


    - name: Build with Hakyll
      working-directory: message-index
      run: cabal run site build
