name: Stack CI

on:
  push:
    paths:
      - 'message-index/site.hs'
      - 'message-index/message-index.cabal'
      - 'message-index/stack.yaml'
      - 'message-index/stack.yaml.lock'
    branches:
      - main
  pull_request:
    paths:
      - 'message-index/site.hs'
      - 'message-index/message-index.cabal'
      - 'message-index/stack.yaml'
      - 'message-index/stack.yaml.lock'
    branches:
      - main

jobs:
  stack-ci:
    name: Stack CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: freckle/stack-action@v4
      with:
        working-directory: message-index
        pedantic: false
